FROM skypilot/aws:latest

ARG PACKAGE_NAME
ARG VERSION
ARG VERSION_POSTFIX
ENV \
  PLATFORM_NAME=${PACKAGE_NAME} \
  PLATFORM_VERSION=${VERSION} \
  PLATFORM_VERSION_POSTFIX=${VERSION_POSTFIX}

RUN mkdir -p \
  /var/lib \
  /var/project

COPY src/ /var/lib/

WORKDIR /var/project

