#!/usr/bin/env bash

# `source` this script to compute variables based on the values generated by `compute-variables.sh`
# Requires aws-cicd >= v0.12

# Change to the directory of this script so that relative paths resolve correctly
cd $(dirname "$0")

THIS_SCRIPT_DIR=$(dirname $(realpath ${PWD}/${BASH_SOURCE[0]}))
cd ${THIS_SCRIPT_DIR} > /dev/null
source ../../lib/aws/aws-functions.sh
source ../../lib/compute-variables.sh
cd - > /dev/null

# Project variables
