---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CI/CD pipeline'

Parameters:
  BranchName:
    Description: 'The source code branch associated with the pipeline'
    Type: String
    Default: 'master'

  CicdArtifactsBucketName:
    Description: 'S3 bucket used for CodeBuild & CodePipeline artifacts'
    Type: String

  CodeBuildEnvironmentImage:
    Description: 'Docker image to use in CodeBuild'
    Type: String

  CodeBuildProjectName:
    Description: 'Name of the CodeBuild project'
    Type: String

  CodeBuildServiceRoleName:
    Description: 'Name of the service role used by CodeBuild to call AWS services'
    Type: String

  CodeBuildServiceRolePolicyName:
    Description: 'Name of the policy attached to the CodeBuild service role'
    Type: String

  CodePipelineName:
    Description: 'Name of the CI/CD pipeline'
    Type: String

  CodePipelineServiceRoleName:
    Description: 'Name of the service role used by CodePipeline to call AWS services'
    Type: String

  DeploymentId:
    Description: 'Identifier of the project, major version, and version stage'
    Type: String

  EventsRuleRandomId:
    Description: 'A unique, user-definied identifier for the target of an Events rule'
    Type: String

  PlatformId:
    Description: 'Identifier of the CI/CD platform'
    Type: String

  ProjectBucketName:
    Description: 'S3 bucket for the project'
    Type: String

  ProjectDescription:
    Description: 'Description of the project'
    Type: String

  ProjectName:
    Description: 'Name of the project (typically same as repo name)'
    Type: String

  RepoName:
    Description: "Name of the CodeCommit repo holding project source code"
    Type: String

Resources:
  EventsRepoChangeRuleStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: CodePipeline
    Properties:
      Parameters:
        BranchName: !Ref BranchName
        CodePipelineArn: !Sub "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${CodePipelineName}"
        CodePipelineName: !Ref CodePipelineName
        DeploymentId: !Ref DeploymentId
        EventsRuleRandomId: !Ref EventsRuleRandomId
        PlatformId: !Ref PlatformId
        ProjectName: !Ref ProjectName
        RepoName: !Ref RepoName
      TemplateURL: './events-repo-change-rule.yml'

  CodeBuildProjectStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        CodeBuildProjectName: !Ref CodeBuildProjectName
        CicdArtifactsBucketName: !Ref CicdArtifactsBucketName
        CodeBuildEnvironmentImage: !Ref CodeBuildEnvironmentImage
        CodeBuildServiceRoleName: !Ref CodeBuildServiceRoleName
        CodeBuildServiceRolePolicyName: !Ref CodeBuildServiceRolePolicyName
        DeploymentId: !Ref DeploymentId
        PlatformId: !Ref PlatformId
        ProjectBucketName: !Ref ProjectBucketName
        ProjectDescription: !Ref ProjectDescription
        RepoName: !Ref RepoName
      TemplateURL: './codebuild-project.yml'
      TimeoutInMinutes: 5

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    DependsOn: CodeBuildProjectStack
    Properties:
      Name: !Ref CodePipelineName
      RoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/${CodePipelineServiceRoleName}"
      Stages:
        - Name: 'Source'
          Actions:
            - Name: 'SourceAction'
              RunOrder: 1
              ActionTypeId:
                Category: 'Source'
                Owner: 'AWS'
                Provider: 'CodeCommit'
                Version: '1'
              Configuration:
                BranchName: !Ref BranchName
                PollForSourceChanges: false
                RepositoryName: !Ref RepoName
              OutputArtifacts:
                - Name: 'SourceOutputArtifact'
        - Name: Build
          Actions:
            - Name: BuildAction
              RunOrder: 1
              InputArtifacts:
                - Name: 'SourceOutputArtifact'
              ActionTypeId:
                Category: 'Build'
                Owner: 'AWS'
                Version: '1'
                Provider: 'CodeBuild'
              Configuration:
                ProjectName: !Ref CodeBuildProjectName
              OutputArtifacts:
                - Name: 'BuildOutputArtifact'
      ArtifactStore:
        Location: !Ref CicdArtifactsBucketName
        Type: 'S3'
