---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS-hosted website served through CloudFront'

Parameters:
  AcmCertificateArn:
    Description: 'ARN ofthe ACM Certificate for the domain'
    Type: String

  ApplicationServerOrigin:
    Description: 'Domain name of the server-side application'
    Type: String

  DeploymentId:
    Description: 'Identifier of the project, major version & version stage'
    Type: String

  PlatformCommitHash:
    Description: 'Commit hash of the CI/CD platform'
    Type: String

  PlatformId:
    Description: 'Identifier of the CI/CD platform name, major version & version stage'
    Type: String

  PlatformVersionLabel:
    Description: 'AWS CI/CD platform version'
    Type: String

  ProjectCommitHash:
    Description: 'Commit hash of the deployed project'
    Type: String

  ProjectVersionLabel:
    Description: 'Project version label (version + stage)'
    Type: String

  SiteDomainName:
    Description: 'Domain name of the site'
    Type: String

  SiteIndexDocument:
    Description: 'Index document'
    Type: String

  StaticFilesBucketName:
    Description: "S3 bucket for the project's static files"
    Type: String

  StaticFilesOrigin:
    Description: 'Domain name of the S3 bucket that serves static files'
    Type: String

  StaticFilesOriginPath:
    Description: 'Path used to request content from the static files endpoint'
    Type: String
    Default: '/static'

  StaticFilesPathPattern:
    Description: 'Pattern describing the path of static files'
    Type: String
    Default: 'static/*'

Resources:
  CdnDistroStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AcmCertificateArn: !Ref AcmCertificateArn
        ApplicationServerOrigin: !Ref ApplicationServerOrigin
        SiteDomainName: !Ref SiteDomainName
        SiteIndexDocument: !Ref SiteIndexDocument
        StaticFilesOrigin: !Ref StaticFilesOrigin
        StaticFilesOriginPath: !Ref StaticFilesOriginPath
        StaticFilesPathPattern: !Ref StaticFilesPathPattern
      TemplateURL: './ecs-cloudfront-distribution.yml'
      TimeoutInMinutes: 60

  StaticFilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref StaticFilesBucketName
