---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Rule triggering the pipeline when the CodeCommit repo is changed'

Parameters:
  BranchName:
    Description: 'The source code branch associated with the pipeline'
    Type: String
    Default: 'master'

  CodePipelineArn:
    Description: 'ARN of the CI/CD pipeline'
    Type: String

  CodePipelineName:
    Description: 'Name of the CI/CD pipeline'
    Type: String

  DeploymentId:
    Description: 'Identifier of the project, major version, and version stage'
    Type: String

  PlatformId:
    Description: 'Identifier of the CI/CD platform'
    Type: String

  ProjectName:
    Description: 'Name of the project (typically same as repo name)'
    Type: String

  EventsRuleRandomId:
    Description: 'A unique, user-definied identifier for the target of an Events rule'
    Type: String

  RepoName:
    Description: "Name of the CodeCommit repo holding project source code"
    Type: String

Resources:
  EventsRepoChangeRule:
    Type: AWS::Events::Rule
    DependsOn: StartPipelineExecutionRole
    Properties:
      Name: !Sub "events-repo-change-rule-${CodePipelineName}"
      Description: 'Rule triggering the pipeline when the CodeCommit repo is changed'
      EventPattern:
        source:
          - 'aws.codecommit'
        detail-type:
          - 'CodeCommit Repository State Change'
        resources:
          - !Sub "arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${RepoName}"
        detail:
          event:
            - 'referenceCreated'
            - 'referenceUpdated'
          referenceType:
            - 'branch'
          referenceName:
            - !Ref BranchName
      Targets:
        - Arn: !Ref CodePipelineArn
          Id: !Ref EventsRuleRandomId
          RoleArn: !GetAtt StartPipelineExecutionRole.Arn

  StartPipelineExecutionRole:
    Type: AWS::IAM::Role
    Description: 'Allows CloudWatch Events to start execution of the code pipeline.'
    Properties:
      RoleName: !Sub "events-start-execution-role-${CodePipelineName}-${AWS::Region}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'events.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub "events-start-pipeline-execution-role-policy-${ProjectName}-${AWS::Region}"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: 'codepipeline:StartPipelineExecution'
                Resource: !Ref CodePipelineArn
