---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS cluster EFS filesystem'

Parameters:
  EcsClusterName:
    Description: 'Name of the ECS cluster'
    Type: String

  FileSystemName:
    Description: 'FileSystem name'
    Type: String

  PlatformCommitHash:
    Description: 'Commit hash of the CI/CD platform'
    Type: String

  PlatformId:
    Description: 'Platform ID'
    Type: String

  PlatformVersionLabel:
    Description: 'AWS CI/CD platform version label (version + stage)'
    Type: String

Resources:
  FileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      FileSystemTags:
        - Key: EcsClusterName
          Value: !Ref EcsClusterName
        - Key: Name
          Value: !Ref FileSystemName

Outputs:
  FileSystemId:
    Description: "ID of the ECS cluster's EFS filesystem"
    Value: !Ref FileSystem
