---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Global platform resources'

Parameters:
  CodePipelineServiceRoleName:
    Description: 'Name of the service role used by CodePipeline to call AWS services'
    Type: String

  PlatformCommitHash:
    Description: 'Commit hash of the CI/CD platform'
    Type: String

  PlatformId:
    Description: "Platform version ID and label"
    Type: String

  PlatformVersionLabel:
    Description: 'AWS CI/CD platform version label (version + stage)'
    Type: String

Resources:
  CodePipelineServiceRoleStack:
    Type: AWS::CloudFormation::Stack
    Description: 'Allows CodePipeline to call AWS services.'
    Properties:
      Parameters:
        CodePipelineServiceRoleName: !Ref CodePipelineServiceRoleName
      TemplateURL: './codepipeline-service-role.yml'
      TimeoutInMinutes: 2
