---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Global platform resources'

Parameters:
  CfnTemplatesBucketName:
    Description: "Name of the S3 bucket for CloudFormation templates"
    Type: String

  CodePipelineServiceRoleName:
    Description: 'Name of the service role used by CodePipeline to call AWS services'
    Type: String

  EcsTasksServiceRoleName:
    Description: 'Name of the service role used by ECS Tasks to call AWS services'
    Type: String

  PlatformCommitHash:
    Description: 'Commit hash of the CI/CD platform'
    Type: String

  PlatformId:
    Description: "Platform version ID and label"
    Type: String

  PlatformVersionLabel:
    Description: 'AWS CI/CD platform version label (version + stage)'
    Type: String

Resources:
  CfnTemplatesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref CfnTemplatesBucketName
      Tags:
        - Key: 'PlatformCommitHash'
          Value: !Ref PlatformCommitHash
        - Key: 'PlatformId'
          Value: !Ref PlatformId
        - Key: 'PlatformVersionLabel'
          Value: !Ref PlatformVersionLabel

  CodePipelineServiceRoleStack:
    Type: AWS::CloudFormation::Stack
    Description: 'Allows CodePipeline to call AWS services.'
    Properties:
      Parameters:
        CodePipelineServiceRoleName: !Ref CodePipelineServiceRoleName
      TemplateURL: './codepipeline-service-role.yml'
      TimeoutInMinutes: 2

  EcsTasksServiceRoleStack:
    Type: AWS::CloudFormation::Stack
    Description: 'Allows ECS Tasks to call AWS services.'
    Properties:
      Parameters:
        EcsTasksServiceRoleName: !Ref EcsTasksServiceRoleName
      TemplateURL: './ecstasks-service-role.yml'
      TimeoutInMinutes: 2
