---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'HTTP domain name redirection'

Parameters:
  PlatformCommitHash:
    Description: 'Commit hash of the CI/CD platform'
    Type: String

  PlatformId:
    Description: 'Platform ID'
    Type: String

  PlatformVersionLabel:
    Description: 'AWS CI/CD platform version label (version + stage)'
    Type: String

  ProjectCommitHash:
    Description: 'Commit hash of the deployed project'
    Type: String

  ProjectVersionLabel:
    Description: 'Project version label (version + stage)'
    Type: String

  SourceDomainName:
    Description: 'Domain name to redirect'
    Type: String

  SourceZoneApex:
    Description: 'Apex of the hosted zone of the target domain name'
    Type: String

  TargetDomainName:
    Description: 'Domain name that is the target of the redirection'
    Type: String

Mappings:
  RegionMap:
    ap-south-1:
      HostedZoneId: 'Z11RGJOFQNVJUP'
    ap-northeast-1:
      HostedZoneId: 'Z2M4EHUR26P7ZW'
    ap-northeast-2:
      HostedZoneId: 'Z3W03O7B5YMIYP'
    ap-northeast-3:
      HostedZoneId: 'Z2YQB5RD63NC85'
    ap-southeast-1:
      HostedZoneId: 'Z3O0J2DXBE1FTB'
    ap-southeast-2:
      HostedZoneId: 'Z1WCIGYICN2BYD'
    ca-central-1:
      HostedZoneId: 'Z1QDHH18159H29'
    eu-central-1:
      HostedZoneId: 'Z21DNDUVLTQW6Q'
    eu-north-1:
      HostedZoneId: 'Z3BAZG2TWCNX0D'
    eu-west-1:
      HostedZoneId: 'Z1BKCTXD74EZPE'
    eu-west-2:
      HostedZoneId: 'Z3GKZC51ZF0DB4'
    eu-west-3:
      HostedZoneId: 'Z3R1K369G5AVDG'
    us-east-1:
      HostedZoneId: 'Z3AQBSTGFYJSTF'
    us-east-2:
      HostedZoneId: 'Z2O1EMRO9K5GLX'
    us-west-1:
      HostedZoneId: 'Z2F56UZL2M1ACD'
    us-west-2:
      HostedZoneId: 'Z3BJ6K6RIION7M'
    sa-east-1:
      HostedZoneId: 'Z7KQH4QJS55SO'

Resources:
  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !Sub "s3-website.${AWS::Region}.amazonaws.com"
        EvaluateTargetHealth: false
        HostedZoneId: !FindInMap [RegionMap, !Ref 'AWS::Region', HostedZoneId]
      HostedZoneName: !Ref SourceZoneApex
      Name: !Ref SourceDomainName
      Type: 'A'

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: 'PublicRead'
      BucketName: !Ref SourceDomainName
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref TargetDomainName
          Protocol: 'https'
