---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 website served through CloudFront'

Parameters:
  AcmCertificateArn:
    Description: 'ARN ofthe ACM Certificate for the domain'
    Type: String

  ApexHostedZoneExists:
    Description: "True if a Route 53 hosted zone exists for the site's apex domain"
    Type: String
    AllowedValues:
      - true
      - false

  CloudFrontHostedZoneId:
    Description: 'Hosted zone ID for CloudFront'
    Type: String

  DeploymentId:
    Description: 'Identifier of the project, major version & version stage'
    Type: String

  PlatformCommitHash:
    Description: 'Commit hash of the CI/CD platform'
    Type: String

  PlatformId:
    Description: 'Identifier of the CI/CD platform name, major version & version stage'
    Type: String

  PlatformVersionLabel:
    Description: 'AWS CI/CD platform version'
    Type: String

  ProjectCommitHash:
    Description: 'Commit hash of the deployed project'
    Type: String

  ProjectVersionLabel:
    Description: 'Project version label (version + stage)'
    Type: String

  SiteBucketName:
    Description: 'S3 bucket for the project'
    Type: String

  SiteDomainName:
    Description: 'Domain name of the site'
    Type: String

  SiteErrorDocument:
    Description: 'Error document'
    Type: String

  SiteIndexDocument:
    Description: 'Index document'
    Type: String

  SourceDomainName:
    Description: 'Domain name to redirect'
    Type: String

  SourceZoneApex:
    Description: 'Apex of the hosted zone of the target domain name'
    Type: String

Conditions:
  CreateAliasToCdn: !Equals [!Ref ApexHostedZoneExists, true]

Resources:
  CdnDistroStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AcmCertificateArn: !Ref AcmCertificateArn
        SiteBucketName: !Ref SiteBucketName
        SiteDomainName: !Ref SiteDomainName
        SiteErrorDocument: !Ref SiteErrorDocument
        SiteIndexDocument: !Ref SiteIndexDocument
      TemplateURL: './s3-cloudfront-distribution.yml'
      TimeoutInMinutes: 60

  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    Condition: CreateAliasToCdn
    Properties:
      AliasTarget:
        DNSName: !GetAtt CdnDistroStack.Outputs.CdnDistroDomainName
        EvaluateTargetHealth: false
        HostedZoneId: !Ref CloudFrontHostedZoneId
      HostedZoneName: !Ref SourceZoneApex
      Name: !Ref SourceDomainName
      Type: 'A'

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: 'PublicRead'
      BucketName: !Ref SiteBucketName
      WebsiteConfiguration:
        ErrorDocument: !Ref SiteErrorDocument
        IndexDocument: !Ref SiteIndexDocument
